= AWS Lambda Labs
:icons: font
:nofooter:
:toc:

:uri-git-repo: https://github.com/paulojeronimo/aws-lambda-labs
:uri-aws-cli: https://aws.amazon.com/cli/
:uri-runtimes-walthrough: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html

In this lab, we’ll be following the steps presented in the
{uri-runtimes-walthrough}["Publishing a custom runtime"] Amazon
tutorial.

== Prerequisites

. A copy of the main branch of {uri-git-repo}[this Git repository].
You can get it by typing the following command in a terminal session:
+
	$ curl -L https://raw.githubusercontent.com/paulojeronimo/aws-lambda-labs/main/download.sh | bash
+
. {uri-aws-cli}[aws-cli] installed.
. A configured IAM user ID (12 digits number) inside a file called
  `config.sh` (copy the file link:config.sample.sh[] to it and edit the
`IAM` variable).

[NOTE]
====
The steps presented below were tested in a macOS environment
running a Bash terminal session. These were the software versions used:

----
$ sw_vers
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91

$ echo $BASH_VERSION
5.1.4(1)-release

$ aws --version
aws-cli/2.1.30 Python/3.9.2 Darwin/20.3.0 source/x86_64 prompt/off
----
====

== Steps

The steps that we’ll be following can be shown by running the following
command:

----
$ ./show-steps.sh
----

We can run each step manually or run all at once by typing the following
command:

----
$ ./run-all-steps.sh
----
