#!/usr/bin/env bash
set -eou pipefail

docker_image_name=$1:amazonlinux
layer_zip=build/layer.zip

echo "Creating the Docker image \"$docker_image_name\" to build \"$layer_zip\" through it ..."
docker build \
	--build-arg layer_zip=${layer_zip##*/} \
	-t $docker_image_name .

echo "Copying the files generated by a container ..."
CONTAINER=$(docker run -d $docker_image_name false)
docker cp ${CONTAINER}:/${layer_zip##*/} $layer_zip

echo "File \"$layer_zip\" successfully generated!"
