= Test script

	$ ./deploy.sh
	$ ./get-logs.sh # <- This will block your terminal session
	$ # go to (or open) another terminal session (shell 2)
	$ ./put-record.sh # <- And wait an ouput on shell 1
	$ ./put-record.sh 'Hello again!' # <- and (again) wait for a new record on shell 1
	$ ./delete.sh # <- will delete the application from AWS

Other local possible scripts tests:

	$ # This will generate JSON files that will be send to S3 bucket:
	$ ./aws-setup.sh generate-bucket-files-locally

	$ # This will test the update of a value read from some JSON file:
	$ ./update-value.sh "New value" < build/bucket-files/01.json

	$ # This will undo de AWS setup:
	$ ./aws-setup.sh undo

	$ # This will delete the app and call the command above:
	$ ./delete.sh -a

Useful command in case of problems when calling the `deploy.sh` script:

	$ aws lambda delete-event-source-mapping --uuid $UUID

References:

* https://github.com/aws/chalice
* https://github.com/aws-samples/chalice-workshop
* https://chalice-workshop.readthedocs.io/en/latest/
* https://github.com/aws/chalice/issues/915
* https://github.com/awsdocs/aws-lambda-developer-guide/tree/main/sample-apps/blank-python
